/// Flutter icons AppSymbols
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppSymbols
///      fonts:
///       - asset: fonts/AppSymbols.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppSymbols {
  AppSymbols._();

  static const _kFontFam = 'AppSymbols';
  static const String? _kFontPkg = null;

  static const IconData coffee_cup = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jug = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drop = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_glass = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
